/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module alternator_3 (
    input clk,
    output reg out
  );
  
  
  
  reg M_bit_d, M_bit_q = 1'h0;
  
  always @* begin
    M_bit_d = M_bit_q;
    
    M_bit_d = ~M_bit_q;
    out = M_bit_q;
  end
  
  always @(posedge clk) begin
    M_bit_q <= M_bit_d;
  end
  
endmodule
