/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module move_counter_8 (
    input clk,
    input rst,
    input [15:0] move_counter_1,
    input [15:0] move_counter_2,
    input [15:0] difficulty,
    output reg [6:0] seg_out,
    output reg [3:0] sel_out
  );
  
  
  
  wire [7-1:0] M_seg_seg;
  wire [4-1:0] M_seg_sel;
  reg [64-1:0] M_seg_values;
  multi_seven_seg_16 seg (
    .clk(clk),
    .rst(rst),
    .values(M_seg_values),
    .seg(M_seg_seg),
    .sel(M_seg_sel)
  );
  
  always @* begin
    M_seg_values[0+15-:16] = move_counter_2;
    M_seg_values[16+15-:16] = move_counter_1;
    M_seg_values[32+15-:16] = 4'ha;
    M_seg_values[48+15-:16] = difficulty;
    seg_out = ~M_seg_seg;
    sel_out = ~M_seg_sel;
  end
endmodule
