/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mux2_10 (
    input [15:0] a,
    input [15:0] b,
    input sel,
    output reg [15:0] out
  );
  
  
  
  always @* begin
    if (~sel) begin
      out = a;
    end else begin
      out = b;
    end
  end
endmodule
