/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module color_adapter_14 (
    input clk,
    input rst,
    input [11:0] state,
    input power_on,
    output reg [287:0] out
  );
  
  
  
  integer i;
  
  localparam EMPTY = 288'h00ff0000ff0000ff0000ff0000ff0000ff0000ff0000ff0000ff0000ff0000ff0000ff00;
  
  reg [287:0] M_led_out_d, M_led_out_q = 288'h00ff0000ff0000ff0000ff0000ff0000ff0000ff0000ff0000ff0000ff0000ff0000ff00;
  
  always @* begin
    M_led_out_d = M_led_out_q;
    
    for (i = 1'h0; i < 4'hc; i = i + 1) begin
      if (power_on) begin
        if (state[(i)*1+0-:1] == 2'h0) begin
          M_led_out_d[(i)*24+23-:24] = 24'hff0000;
        end else begin
          M_led_out_d[(i)*24+23-:24] = 24'h00ff00;
        end
      end else begin
        M_led_out_d[(i)*24+23-:24] = 24'h000000;
      end
      out[(i)*24+23-:24] = M_led_out_q[(i)*24+23-:24];
    end
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_led_out_q <= 288'h00ff0000ff0000ff0000ff0000ff0000ff0000ff0000ff0000ff0000ff0000ff0000ff00;
    end else begin
      M_led_out_q <= M_led_out_d;
    end
  end
  
endmodule
