/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module difficulty_level_control_4 (
    input clk,
    input rst,
    input update_difficulty,
    input update_move,
    input reset_counter,
    output reg [1:0] hidden_turns,
    output reg [1:0] difficulty
  );
  
  
  
  reg [1:0] M_difficulty_level_d, M_difficulty_level_q = 1'h0;
  
  reg [1:0] M_turns_hidden_left_d, M_turns_hidden_left_q = 1'h0;
  
  always @* begin
    M_difficulty_level_d = M_difficulty_level_q;
    M_turns_hidden_left_d = M_turns_hidden_left_q;
    
    if (update_difficulty) begin
      if (M_difficulty_level_q == 2'h2) begin
        M_difficulty_level_d = 2'h0;
        M_turns_hidden_left_d = 1'h0;
      end else begin
        M_difficulty_level_d = M_difficulty_level_q + 1'h1;
      end
    end
    if (update_move) begin
      if (M_turns_hidden_left_q == 2'h0) begin
        M_turns_hidden_left_d = M_difficulty_level_q;
      end else begin
        M_turns_hidden_left_d = M_turns_hidden_left_q - 1'h1;
      end
    end
    if (reset_counter) begin
      M_turns_hidden_left_d = 2'h0;
    end
    difficulty = M_difficulty_level_q + 1'h1;
    hidden_turns = M_turns_hidden_left_q;
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_difficulty_level_q <= 1'h0;
    end else begin
      M_difficulty_level_q <= M_difficulty_level_d;
    end
  end
  
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_turns_hidden_left_q <= 1'h0;
    end else begin
      M_turns_hidden_left_q <= M_turns_hidden_left_d;
    end
  end
  
endmodule
