/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module display_encoder_19 (
    input [15:0] state,
    output reg [11:0] strip0,
    output reg [11:0] strip1,
    output reg [11:0] strip2,
    output reg [11:0] strip3
  );
  
  
  
  always @* begin
    strip0[0+2-:3] = {2'h3{state[0+0-:1]}};
    strip0[3+2-:3] = {2'h3{state[1+0-:1]}};
    strip0[6+2-:3] = {2'h3{state[2+0-:1]}};
    strip0[9+2-:3] = {2'h3{state[3+0-:1]}};
    strip1[0+2-:3] = {2'h3{state[4+0-:1]}};
    strip1[3+2-:3] = {2'h3{state[5+0-:1]}};
    strip1[6+2-:3] = {2'h3{state[6+0-:1]}};
    strip1[9+2-:3] = {2'h3{state[7+0-:1]}};
    strip2[0+2-:3] = {2'h3{state[8+0-:1]}};
    strip2[3+2-:3] = {2'h3{state[9+0-:1]}};
    strip2[6+2-:3] = {2'h3{state[10+0-:1]}};
    strip2[9+2-:3] = {2'h3{state[11+0-:1]}};
    strip3[0+2-:3] = {2'h3{state[12+0-:1]}};
    strip3[3+2-:3] = {2'h3{state[13+0-:1]}};
    strip3[6+2-:3] = {2'h3{state[14+0-:1]}};
    strip3[9+2-:3] = {2'h3{state[15+0-:1]}};
  end
endmodule
