/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module regfile_7 (
    input clk,
    input [3:0] read_address_1,
    input [3:0] read_address_2,
    output reg [15:0] read_data_1,
    output reg [15:0] read_data_2,
    input [3:0] write_address,
    input [15:0] write_data,
    input write_enable,
    output reg [15:0] board_state,
    output reg [15:0] initial_board_state_index,
    output reg [15:0] move_count_1,
    output reg [15:0] move_count_2,
    output reg [15:0] difficulty_level,
    output reg [15:0] hidden_turns_left,
    output reg [15:0] game_over
  );
  
  
  
  reg [159:0] M_registers_d, M_registers_q = 160'h0000000000000000000000000000000000000000;
  
  always @* begin
    M_registers_d = M_registers_q;
    
    read_data_1 = M_registers_q[(read_address_1)*16+15-:16];
    read_data_2 = M_registers_q[(read_address_2)*16+15-:16];
    if (read_address_1 == 3'h7) begin
      read_data_1 = 16'h0000;
    end
    if (read_address_1 == 4'h8) begin
      read_data_1 = 1'h1;
    end
    if (read_address_1 == 4'h9) begin
      read_data_1 = 16'hffff;
    end
    if (read_address_2 == 3'h7) begin
      read_data_2 = 16'h0000;
    end
    if (read_address_2 == 4'h8) begin
      read_data_2 = 1'h1;
    end
    if (read_address_2 == 4'h9) begin
      read_data_2 = 16'hffff;
    end
    if (write_enable) begin
      M_registers_d[(write_address)*16+15-:16] = write_data;
    end
    board_state = M_registers_q[0+15-:16];
    initial_board_state_index = M_registers_q[16+15-:16];
    move_count_1 = M_registers_q[32+15-:16];
    move_count_2 = M_registers_q[48+15-:16];
    difficulty_level = M_registers_q[64+15-:16];
    hidden_turns_left = M_registers_q[80+15-:16];
    game_over = M_registers_q[96+15-:16];
  end
  
  always @(posedge clk) begin
    M_registers_q <= M_registers_d;
  end
  
endmodule
